### ISSUE TITLE
already_pixel_swapped flag, use proper data-swapped attribute format

### ISSUE THREAD

**Issue by gregallensworth** [GreenInfo-Network/L.TileLayer.PixelFilter#1]
applyFiltersToTile() sets the already_pixel_swapped attribute on the IMG element, to indicate that it has been processed.

This should surely be a _data-_ attribute so it could not possibly conflict with any potential future attribute.

```
if ( imgelement.getAttribute('data-already-pixel-swapped') ) return;

imgelement.setAttribute('data-already-pixel-swapped', true );
```

**Comment by greeninfo** [comment]
All set. it now uses a prop data attribute: **data-PixelFilterDone**
