### ISSUE TITLE
Support a matchRGBA or missRGBA to copy the pixel as-is

### ISSUE THREAD

**Issue by gregallensworth** [GreenInfo-Network/L.TileLayer.PixelFilter#2]
Allow null to be explicitly given for matchRGBA or missRGBA. In this case, copy the existing pixel RGBA codes.

This would allow pixels to be swapped... or preserved. In the case of color-classified rasters such as in the demo, this would allow hits to show using their native color and misses to be hidden (or vice versa).

**Comment by greeninfo** [comment]
All set. Updated the code, and the demos, and the docs.

This new capability is really neat.
