### ISSUE TITLE
Cross Origin Issue

### ISSUE THREAD

**Issue by hnrchrdl** [GreenInfo-Network/L.TileLayer.PixelFilter#9]
I had an issue with canvas complaining about cross origin requests when calling `context.getImageData`. I fixed it on my fork, I can send you the pull request if you like.
Basically, I had to explicitly set `options.crossOrigin = true;` . In the [Grayscale Plugin](https://github.com/Zverik/leaflet-grayscale/blob/master/TileLayer.Grayscale.js), there is the same built in, so I guess it should work in general terms. I belief this issue came up with v.1 of leaflet.

**Comment by gregallensworth** [comment]
I would love to see your PR. I thought that we had cross-domain stuff working well with the `cross-origin='anonymous'` setting at https://github.com/GreenInfo-Network/L.TileLayer.PixelFilter/blob/master/leaflet-tileLayerPixelFilter.js#L61  But if you have additional improvements, I would be glad to check them out.

Thank you for asking.
